-- LLM Wiki local index schema (SQLite + FTS5)
-- This is derived state — deletable and rebuildable from the workspace filesystem.
--
-- DATA BOUNDARY CLASSIFICATION (per truth-data-persistence-boundary spec):
--
-- FILE TRUTH (canonical, persisted to filesystem):
--   documents.content       → markdown file content
--   documents.filename      → derived from file path
--   documents.title         → frontmatter title or filename-derived
--   documents.path          → directory path on disk
--   documents.relative_path → relative to workspace root
--   documents.source_kind   → inferred from path prefix (wiki/ vs raw/)
--   documents.file_type     → derived from file extension
--   documents.file_size     → from filesystem stat
--   documents.tags          → from YAML frontmatter
--   documents.date          → from YAML frontmatter
--   documents.metadata      → from YAML frontmatter (description, etc.)
--   documents.content_hash  → SHA-256 of file bytes
--
-- DB-DERIVED (rebuildable, can be fully reconstructed from file truth):
--   document_chunks         → generated by chunking engine from content
--   chunks_fts              → FTS5 index derived from document_chunks
--   document_references     → parsed from markdown links and citations
--   documents.status        → tracking field, reset on reindex
--   documents.version       → incremented on updates
--   documents.parser        → records which parser was used
--   documents.stale_since   → staleness propagation tracking
--   documents.highlights    → user highlights (UI-managed)
--   documents.page_count    → computed during parsing
--   documents.error_message → error tracking
--   documents.mtime_ns      → filesystem mtime cache for watcher
--   documents.last_indexed_at → indexing timestamp
--   documents.document_number → ordering field
--   documents.user_id       → always 'default' for single-user mode
--
-- DB-CACHED (optional performance mirror of file truth, non-authoritative):
--   documents.content       → cached copy for search/convenience
--   documents.title         → cached copy for query convenience
--   documents.tags (JSON)   → cached copy of frontmatter array
--
-- RULE: On reindex, all DB content is dropped and rebuilt from filesystem.
-- If DB-cached data diverges from files, files prevail.

PRAGMA journal_mode=WAL;
PRAGMA foreign_keys=ON;

CREATE TABLE IF NOT EXISTS workspace (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT DEFAULT '',
    user_id TEXT NOT NULL,
    created_at TEXT DEFAULT (datetime('now')),
    UNIQUE(user_id)
);

CREATE TABLE IF NOT EXISTS documents (
    id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
    user_id TEXT NOT NULL,
    filename TEXT NOT NULL,
    title TEXT,
    path TEXT DEFAULT '/' NOT NULL,
    relative_path TEXT NOT NULL,
    source_kind TEXT NOT NULL CHECK (source_kind IN ('wiki', 'source', 'asset')),
    file_type TEXT NOT NULL,
    file_size INTEGER DEFAULT 0,
    document_number INTEGER,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'ready', 'failed')),
    page_count INTEGER,
    content TEXT,
    tags TEXT DEFAULT '[]',
    date TEXT,
    metadata TEXT,
    error_message TEXT,
    version INTEGER DEFAULT 0,
    parser TEXT,
    content_hash TEXT,
    mtime_ns INTEGER,
    last_indexed_at TEXT,
    stale_since TEXT,
    highlights TEXT DEFAULT '[]',
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now')),
    UNIQUE(relative_path)
);

CREATE TABLE IF NOT EXISTS document_pages (
    id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
    document_id TEXT NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    page INTEGER NOT NULL,
    content TEXT NOT NULL,
    elements TEXT,
    UNIQUE(document_id, page)
);

CREATE TABLE IF NOT EXISTS document_chunks (
    id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
    document_id TEXT NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    chunk_index INTEGER NOT NULL,
    content TEXT NOT NULL,
    page INTEGER,
    start_char INTEGER,
    token_count INTEGER NOT NULL,
    header_breadcrumb TEXT,
    created_at TEXT DEFAULT (datetime('now')),
    UNIQUE(document_id, chunk_index)
);

CREATE TABLE IF NOT EXISTS document_references (
    id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
    source_document_id TEXT NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    target_document_id TEXT NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    reference_type TEXT NOT NULL CHECK (reference_type IN ('cites', 'links_to')),
    page INTEGER,
    UNIQUE(source_document_id, target_document_id, reference_type)
);

CREATE TABLE IF NOT EXISTS ingest_jobs (
    id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
    parent_job_id TEXT REFERENCES ingest_jobs(id) ON DELETE SET NULL,
    input_type TEXT NOT NULL DEFAULT 'file',
    source_path TEXT NOT NULL,
    source_ref TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'queued' CHECK (
        status IN (
            'queued', 'running', 'succeeded', 'failed', 'cancelled',
            'pending', 'processing', 'done'
        )
    ),
    retries INTEGER NOT NULL DEFAULT 0,
    max_retries INTEGER NOT NULL DEFAULT 3,
    error TEXT NOT NULL DEFAULT '',
    error_code TEXT NOT NULL DEFAULT '',
    error_message TEXT NOT NULL DEFAULT '',
    missing_dependency TEXT NOT NULL DEFAULT '',
    remediation TEXT NOT NULL DEFAULT '',
    result_summary TEXT NOT NULL DEFAULT '',
    runner_id TEXT NOT NULL DEFAULT '',
    heartbeat_at TEXT NOT NULL DEFAULT '',
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS ingest_job_events (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    job_id TEXT NOT NULL REFERENCES ingest_jobs(id) ON DELETE CASCADE,
    step TEXT NOT NULL,
    phase TEXT NOT NULL,
    message TEXT NOT NULL DEFAULT '',
    payload TEXT NOT NULL DEFAULT '',
    created_at TEXT DEFAULT (datetime('now'))
);

-- FTS5 full-text search over document chunks
-- Using external content mode: FTS5 stores only the index, text lives in document_chunks
CREATE VIRTUAL TABLE IF NOT EXISTS chunks_fts USING fts5(
    content,
    content='document_chunks',
    content_rowid='rowid',
    tokenize='trigram'
);

-- Keep FTS in sync with document_chunks automatically
CREATE TRIGGER IF NOT EXISTS chunks_fts_insert AFTER INSERT ON document_chunks BEGIN
    INSERT INTO chunks_fts(rowid, content) VALUES (new.rowid, new.content);
END;

CREATE TRIGGER IF NOT EXISTS chunks_fts_delete AFTER DELETE ON document_chunks BEGIN
    INSERT INTO chunks_fts(chunks_fts, rowid, content) VALUES('delete', old.rowid, old.content);
END;

CREATE TRIGGER IF NOT EXISTS chunks_fts_update AFTER UPDATE ON document_chunks BEGIN
    INSERT INTO chunks_fts(chunks_fts, rowid, content) VALUES('delete', old.rowid, old.content);
    INSERT INTO chunks_fts(rowid, content) VALUES (new.rowid, new.content);
END;

-- Indexes
CREATE INDEX IF NOT EXISTS idx_documents_relative_path ON documents(relative_path);
CREATE INDEX IF NOT EXISTS idx_documents_path ON documents(path);
CREATE INDEX IF NOT EXISTS idx_documents_source_kind ON documents(source_kind);
CREATE INDEX IF NOT EXISTS idx_documents_status ON documents(status);
CREATE INDEX IF NOT EXISTS idx_chunks_doc ON document_chunks(document_id);
CREATE INDEX IF NOT EXISTS idx_refs_source ON document_references(source_document_id);
CREATE INDEX IF NOT EXISTS idx_refs_target ON document_references(target_document_id);
CREATE INDEX IF NOT EXISTS idx_ingest_jobs_status ON ingest_jobs(status);
CREATE INDEX IF NOT EXISTS idx_ingest_jobs_created_at ON ingest_jobs(created_at);
CREATE UNIQUE INDEX IF NOT EXISTS idx_ingest_one_running ON ingest_jobs(status) WHERE status = 'running';
CREATE INDEX IF NOT EXISTS idx_job_events_job_id ON ingest_job_events(job_id, id DESC);

CREATE TABLE IF NOT EXISTS ingest_sessions (
    id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
    title TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'archived')),
    storage_path TEXT NOT NULL DEFAULT '',
    llm_instance_id TEXT NOT NULL DEFAULT '',
    llm_model TEXT NOT NULL DEFAULT '',
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS ingest_session_messages (
    id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
    session_id TEXT NOT NULL REFERENCES ingest_sessions(id) ON DELETE CASCADE,
    role TEXT NOT NULL CHECK (role IN ('user', 'assistant', 'system')),
    content TEXT NOT NULL DEFAULT '',
    message_type TEXT NOT NULL DEFAULT 'text' CHECK (message_type IN ('text', 'attachment_summary')),
    attachment_id TEXT NOT NULL DEFAULT '',
    stream_status TEXT NOT NULL DEFAULT 'complete' CHECK (
        stream_status IN ('streaming', 'complete', 'incomplete', 'failed')
    ),
    created_at TEXT DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_ingest_session_messages_session
    ON ingest_session_messages(session_id, datetime(created_at));

CREATE TABLE IF NOT EXISTS ingest_session_references (
    id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
    session_id TEXT NOT NULL REFERENCES ingest_sessions(id) ON DELETE CASCADE,
    document_id TEXT NOT NULL,
    relative_path TEXT NOT NULL DEFAULT '',
    title TEXT NOT NULL DEFAULT '',
    source TEXT NOT NULL CHECK (source IN ('user_mention', 'tool_read')),
    first_seen_at TEXT DEFAULT (datetime('now')),
    UNIQUE(session_id, document_id)
);

CREATE INDEX IF NOT EXISTS idx_ingest_session_refs_session
    ON ingest_session_references(session_id, datetime(first_seen_at));

CREATE TABLE IF NOT EXISTS ingest_reviews (
    id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
    session_id TEXT NOT NULL DEFAULT '',
    archive_source_path TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'planning' CHECK (
        status IN (
            'planning', 'ready_for_review', 'revising', 'approved',
            'applying', 'succeeded', 'failed', 'cancelled'
        )
    ),
    current_plan_version INTEGER NOT NULL DEFAULT 0,
    approved_plan_version INTEGER NOT NULL DEFAULT 0,
    final_job_id TEXT NOT NULL DEFAULT '',
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS ingest_review_messages (
    id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
    review_id TEXT NOT NULL REFERENCES ingest_reviews(id) ON DELETE CASCADE,
    role TEXT NOT NULL CHECK (role IN ('user', 'assistant', 'system')),
    message_type TEXT NOT NULL DEFAULT 'feedback' CHECK (
        message_type IN ('feedback', 'plan_summary', 'status_note')
    ),
    content TEXT NOT NULL DEFAULT '',
    created_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS ingest_review_plans (
    id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
    review_id TEXT NOT NULL REFERENCES ingest_reviews(id) ON DELETE CASCADE,
    version INTEGER NOT NULL,
    plan_markdown TEXT NOT NULL DEFAULT '',
    plan_json TEXT NOT NULL DEFAULT '',
    created_at TEXT DEFAULT (datetime('now')),
    UNIQUE(review_id, version)
);

CREATE INDEX IF NOT EXISTS idx_ingest_reviews_status ON ingest_reviews(status);
CREATE INDEX IF NOT EXISTS idx_ingest_reviews_session ON ingest_reviews(session_id);
CREATE INDEX IF NOT EXISTS idx_ingest_review_messages_review ON ingest_review_messages(review_id, datetime(created_at));
CREATE INDEX IF NOT EXISTS idx_ingest_review_plans_review ON ingest_review_plans(review_id, version);

-- Application configuration key-value store
CREATE TABLE IF NOT EXISTS app_config (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL DEFAULT '',
    updated_at TEXT DEFAULT (datetime('now'))
);

-- Provider instances: user-added provider configurations with custom names
CREATE TABLE IF NOT EXISTS provider_instances (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    catalog_id TEXT NOT NULL,
    api_key TEXT NOT NULL DEFAULT '',
    base_url TEXT NOT NULL DEFAULT '',
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
);

-- Per-provider API keys and optional base URL overrides (DEPRECATED: use provider_instances)
CREATE TABLE IF NOT EXISTS provider_keys (
    provider_id TEXT PRIMARY KEY,
    api_key TEXT NOT NULL DEFAULT '',
    base_url TEXT NOT NULL DEFAULT '',
    updated_at TEXT DEFAULT (datetime('now'))
);

-- Cached provider metadata from models.dev (or built-in snapshot)
CREATE TABLE IF NOT EXISTS provider_info_cache (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL DEFAULT '',
    api_base TEXT NOT NULL DEFAULT '',
    api_format TEXT NOT NULL DEFAULT 'openai' CHECK (api_format IN ('openai', 'anthropic', 'ollama')),
    env_key TEXT NOT NULL DEFAULT '',
    doc_url TEXT NOT NULL DEFAULT ''
);

-- Cached model metadata from models.dev (or built-in snapshot)
CREATE TABLE IF NOT EXISTS provider_models_cache (
    provider_id TEXT NOT NULL,
    model_id TEXT NOT NULL,
    name TEXT NOT NULL DEFAULT '',
    family TEXT NOT NULL DEFAULT '',
    context_limit INTEGER NOT NULL DEFAULT 0,
    output_limit INTEGER NOT NULL DEFAULT 0,
    cost_input REAL NOT NULL DEFAULT 0,
    cost_output REAL NOT NULL DEFAULT 0,
    reasoning INTEGER NOT NULL DEFAULT 0,
    tool_call INTEGER NOT NULL DEFAULT 0,
    attachment INTEGER NOT NULL DEFAULT 0,
    modalities TEXT NOT NULL DEFAULT '{}',
    PRIMARY KEY (provider_id, model_id)
);

CREATE INDEX IF NOT EXISTS idx_provider_models_provider ON provider_models_cache(provider_id);

-- OPERATIONAL: activity_logs — system audit trail, NOT rebuildable from filesystem.
-- reindex MUST NOT delete or rebuild this table.
CREATE TABLE IF NOT EXISTS activity_logs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at TEXT DEFAULT (datetime('now')),
    level TEXT NOT NULL DEFAULT 'info' CHECK (level IN ('debug', 'info', 'warn', 'error')),
    category TEXT NOT NULL,
    action TEXT NOT NULL,
    message TEXT NOT NULL DEFAULT '',
    resource_type TEXT NOT NULL DEFAULT '',
    resource_id TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT '',
    details TEXT NOT NULL DEFAULT '',
    source TEXT NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_activity_logs_created_at ON activity_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_activity_logs_category_created_at ON activity_logs(category, created_at DESC);
